name: Build
on: [push, pull_request]
jobs:

  build:
    name: Build bot
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.14, 1.15]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build bot
        working-directory: ./cmd/bot
        run: go build -v
