---
name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Build bot
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [1.15, 1.16]

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2.2.0
        with:
          go-version: ${{ matrix.go }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.4.0

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build bot
        working-directory: ./cmd/bot
        run: go build -v
