---
name: Build web

on:
  push:
    branches:
      - master
  pull_request:

permissions: {}

jobs:
  build:
    name: Build web
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["18", "20", "22", "23"]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node }}

      - working-directory: ./web
        run: npm ci

      - working-directory: ./web
        run: npm run check_formatting

      - working-directory: ./web
        run: npm run build
